# server/Dockerfile
FROM node:20-alpine
WORKDIR /app

# Install dependencies first for better caching
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Install ts-node globally for running TypeScript directly
RUN npm install -g ts-node

# Serve
EXPOSE 4200
CMD ["npm", "start"]
